import type { Td3PaletteLayer } from '../../shared/td3-image.js';

export type Td3ImageStatus = 'ready' | 'guessed' | 'skipped';
export type Td3PaletteStrategy = 'default-vga' | 'single' | 'layered' | 'unresolved';

export interface Td3ImageManifestEntry {
    readonly id: string;
    readonly datFile: string;
    readonly offset: number;
    readonly size: number;
    readonly width?: number;
    readonly height?: number;
    readonly filename?: string;
    readonly format: 'image';
    readonly compression: 'lzw+rle';
    readonly description: string;
    readonly paletteStrategy: Td3PaletteStrategy;
    readonly paletteRefs: readonly string[];
    readonly paletteLayers: readonly Td3PaletteLayer[];
    readonly paletteBase: number;
    readonly pixelBase: number;
    readonly status: Td3ImageStatus;
    readonly skipReason?: string;
    readonly guessReason?: string;
    readonly notes: readonly string[];
}

interface EntryInput {
    readonly datFile: string;
    readonly offset: number;
    readonly size: number;
    readonly width?: number;
    readonly height?: number;
    readonly filename?: string;
    readonly description: string;
    readonly paletteStrategy: Td3PaletteStrategy;
    readonly paletteRefs?: readonly string[];
    readonly paletteLayers?: readonly Td3PaletteLayer[];
    readonly paletteBase?: number;
    readonly pixelBase?: number;
    readonly status?: Td3ImageStatus;
    readonly skipReason?: string;
    readonly guessReason?: string;
    readonly notes?: readonly string[];
}

const HIGH_BANK_BASE = 144;
const HIGH_BANK_PIXEL_BASE = 128;
const LOW_BANK_BASE = 16;
const LOW_BANK_PIXEL_BASE = 0;

function layer(datFile: string, offset: number, baseIndex: number, colorCount: number, label: string): Td3PaletteLayer {
    return { datFile, offset, baseIndex, colorCount, label };
}

function sameFile112(datFile: string, offset: number, baseIndex: number, label: string): Td3PaletteLayer[] {
    return [layer(datFile, offset, baseIndex, 112, label)];
}

function entry(input: EntryInput): Td3ImageManifestEntry {
    return {
        id: `${input.datFile}:0x${input.offset.toString(16).toUpperCase()}`,
        datFile: input.datFile,
        offset: input.offset,
        size: input.size,
        width: input.width,
        height: input.height,
        filename: input.filename,
        format: 'image',
        compression: 'lzw+rle',
        description: input.description,
        paletteStrategy: input.paletteStrategy,
        paletteRefs: input.paletteRefs ?? [],
        paletteLayers: input.paletteLayers ?? [],
        paletteBase: input.paletteBase ?? 0,
        pixelBase: input.pixelBase ?? 0,
        status: input.status ?? 'ready',
        skipReason: input.skipReason,
        guessReason: input.guessReason,
        notes: input.notes ?? [],
    };
}

function carEntries(datFile: string, sicHeight: number, entries: readonly [number, number, string, number, number, string, string][]): Td3ImageManifestEntry[] {
    return entries.map(([offset, size, filename, width, height, group, description]) => {
        if (group === 'SC') {
            return entry({
                datFile,
                offset,
                size,
                width,
                height,
                filename,
                description,
                paletteStrategy: 'single',
                paletteRefs: [`${datFile}@0x00000 (${datFile.replace('.DAT', 'SC.BIN')})`],
                paletteLayers: sameFile112(datFile, 0x00000, HIGH_BANK_BASE, `${datFile} SC palette`),
                paletteBase: HIGH_BANK_BASE,
                pixelBase: HIGH_BANK_PIXEL_BASE,
            });
        }

        if (group === 'COL') {
            return entry({
                datFile,
                offset,
                size,
                width,
                height,
                filename,
                description,
                paletteStrategy: 'single',
                paletteRefs: [`${datFile}@0x00151 (${datFile.replace('.DAT', 'COL.BIN')})`],
                paletteLayers: sameFile112(datFile, 0x00151, HIGH_BANK_BASE, `${datFile} COL palette`),
                paletteBase: HIGH_BANK_BASE,
                pixelBase: HIGH_BANK_PIXEL_BASE,
            });
        }

        return entry({
            datFile,
            offset,
            size,
            width,
            height: sicHeight,
            filename,
            description,
            paletteStrategy: 'layered',
            paletteRefs: [
                'DATAC.DAT@0x00000 (SELCOLR.BIN)',
                `${datFile}@0x002A2 (${datFile.replace('.DAT', 'SIC.BIN')})`,
            ],
            paletteLayers: [
                layer('DATAC.DAT', 0x00000, HIGH_BANK_BASE, 112, 'SELCOLR.BIN'),
                layer(datFile, 0x002A2, 192, 32, `${datFile} SIC overlay`),
            ],
            paletteBase: HIGH_BANK_BASE,
            pixelBase: HIGH_BANK_PIXEL_BASE,
        });
    });
}

export const td3ImageManifest: readonly Td3ImageManifestEntry[] = [
    entry({
        datFile: 'SCENE01.DAT',
        offset: 0x00000,
        size: 0x0299,
        width: 320,
        height: 33,
        description: 'Route title image',
        paletteStrategy: 'default-vga',
        paletteRefs: ['default VGA palette'],
        status: 'guessed',
        guessReason: 'Pixels stay in the base VGA range, so this is guessed as a default-VGA title image.',
    }),
    entry({
        datFile: 'SCENE01.DAT',
        offset: 0x0029A,
        size: 0x01C0,
        width: 72,
        height: 40,
        description: 'Route icon image',
        paletteStrategy: 'default-vga',
        paletteRefs: ['default VGA palette'],
        status: 'guessed',
        guessReason: 'Pixels stay in the base VGA range, so this is guessed as a default-VGA icon image.',
    }),
    entry({
        datFile: 'SCENE01.DAT',
        offset: 0x124C9,
        size: 0x1D6A,
        width: 320,
        height: 50,
        description: 'Landscape block A',
        paletteStrategy: 'single',
        paletteRefs: ['SCENE01.DAT@0x12378'],
        paletteLayers: sameFile112('SCENE01.DAT', 0x12378, LOW_BANK_BASE, 'SCENE01.DAT palette A'),
        paletteBase: LOW_BANK_BASE,
        pixelBase: LOW_BANK_PIXEL_BASE,
    }),
    entry({
        datFile: 'SCENE01.DAT',
        offset: 0x14234,
        size: 0x125B,
        width: 320,
        height: 19,
        description: 'Landscape block B',
        paletteStrategy: 'single',
        paletteRefs: ['SCENE01.DAT@0x12378'],
        paletteLayers: sameFile112('SCENE01.DAT', 0x12378, LOW_BANK_BASE, 'SCENE01.DAT palette A'),
        paletteBase: LOW_BANK_BASE,
        pixelBase: LOW_BANK_PIXEL_BASE,
    }),
    entry({
        datFile: 'SCENE01.DAT',
        offset: 0x1E5A2,
        size: 0x1C09,
        width: 320,
        height: 50,
        description: 'Landscape block C',
        paletteStrategy: 'single',
        paletteRefs: ['SCENE01.DAT@0x1E451'],
        paletteLayers: sameFile112('SCENE01.DAT', 0x1E451, LOW_BANK_BASE, 'SCENE01.DAT palette B'),
        paletteBase: LOW_BANK_BASE,
        pixelBase: LOW_BANK_PIXEL_BASE,
    }),
    entry({
        datFile: 'SCENE01.DAT',
        offset: 0x201AC,
        size: 0x13B8,
        width: 320,
        height: 19,
        description: 'Landscape block D',
        paletteStrategy: 'single',
        paletteRefs: ['SCENE01.DAT@0x1E451'],
        paletteLayers: sameFile112('SCENE01.DAT', 0x1E451, LOW_BANK_BASE, 'SCENE01.DAT palette B'),
        paletteBase: LOW_BANK_BASE,
        pixelBase: LOW_BANK_PIXEL_BASE,
    }),
    entry({
        datFile: 'SCENE01.DAT',
        offset: 0x2593B,
        size: 0x2C56,
        width: 320,
        height: 50,
        description: 'Landscape block E',
        paletteStrategy: 'single',
        paletteRefs: ['SCENE01.DAT@0x257EA'],
        paletteLayers: sameFile112('SCENE01.DAT', 0x257EA, LOW_BANK_BASE, 'SCENE01.DAT palette C'),
        paletteBase: LOW_BANK_BASE,
        pixelBase: LOW_BANK_PIXEL_BASE,
    }),
    entry({
        datFile: 'SCENE01.DAT',
        offset: 0x28592,
        size: 0x1052,
        width: 320,
        height: 19,
        description: 'Landscape block F',
        paletteStrategy: 'single',
        paletteRefs: ['SCENE01.DAT@0x257EA'],
        paletteLayers: sameFile112('SCENE01.DAT', 0x257EA, LOW_BANK_BASE, 'SCENE01.DAT palette C'),
        paletteBase: LOW_BANK_BASE,
        pixelBase: LOW_BANK_PIXEL_BASE,
    }),
    entry({
        datFile: 'SCENE02.DAT',
        offset: 0x00000,
        size: 0x02BC,
        width: 320,
        height: 33,
        description: 'Route title image',
        paletteStrategy: 'default-vga',
        paletteRefs: ['default VGA palette'],
        status: 'guessed',
        guessReason: 'Pixels stay in the base VGA range, so this is guessed as a default-VGA title image.',
    }),
    entry({
        datFile: 'SCENE02.DAT',
        offset: 0x002BD,
        size: 0x01CA,
        width: 72,
        height: 40,
        description: 'Route icon image',
        paletteStrategy: 'default-vga',
        paletteRefs: ['default VGA palette'],
        status: 'guessed',
        guessReason: 'Pixels stay in the base VGA range, so this is guessed as a default-VGA icon image.',
    }),
    entry({
        datFile: 'SCENE02.DAT',
        offset: 0x23818,
        size: 0x2171,
        width: 320,
        height: 50,
        description: 'Landscape block A',
        paletteStrategy: 'single',
        paletteRefs: ['SCENE02.DAT@0x236C7'],
        paletteLayers: sameFile112('SCENE02.DAT', 0x236C7, LOW_BANK_BASE, 'SCENE02.DAT palette A'),
        paletteBase: LOW_BANK_BASE,
        pixelBase: LOW_BANK_PIXEL_BASE,
    }),
    entry({
        datFile: 'SCENE02.DAT',
        offset: 0x2598A,
        size: 0x08E8,
        width: 320,
        height: 19,
        description: 'Landscape block B',
        paletteStrategy: 'single',
        paletteRefs: ['SCENE02.DAT@0x236C7'],
        paletteLayers: sameFile112('SCENE02.DAT', 0x236C7, LOW_BANK_BASE, 'SCENE02.DAT palette A'),
        paletteBase: LOW_BANK_BASE,
        pixelBase: LOW_BANK_PIXEL_BASE,
    }),
    entry({
        datFile: 'SCENE02.DAT',
        offset: 0x2A649,
        size: 0x2318,
        width: 320,
        height: 50,
        description: 'Landscape block C',
        paletteStrategy: 'single',
        paletteRefs: ['SCENE02.DAT@0x2A4F8'],
        paletteLayers: sameFile112('SCENE02.DAT', 0x2A4F8, LOW_BANK_BASE, 'SCENE02.DAT palette B'),
        paletteBase: LOW_BANK_BASE,
        pixelBase: LOW_BANK_PIXEL_BASE,
    }),
    entry({
        datFile: 'SCENE02.DAT',
        offset: 0x2C962,
        size: 0x0F19,
        width: 320,
        height: 19,
        description: 'Landscape block D',
        paletteStrategy: 'single',
        paletteRefs: ['SCENE02.DAT@0x2A4F8'],
        paletteLayers: sameFile112('SCENE02.DAT', 0x2A4F8, LOW_BANK_BASE, 'SCENE02.DAT palette B'),
        paletteBase: LOW_BANK_BASE,
        pixelBase: LOW_BANK_PIXEL_BASE,
    }),
    entry({
        datFile: 'SCENE02.DAT',
        offset: 0x2FB05,
        size: 0x27DA,
        width: 320,
        height: 50,
        description: 'Landscape block E',
        paletteStrategy: 'single',
        paletteRefs: ['SCENE02.DAT@0x2F9B4'],
        paletteLayers: sameFile112('SCENE02.DAT', 0x2F9B4, LOW_BANK_BASE, 'SCENE02.DAT palette C'),
        paletteBase: LOW_BANK_BASE,
        pixelBase: LOW_BANK_PIXEL_BASE,
    }),
    entry({
        datFile: 'SCENE02.DAT',
        offset: 0x322E0,
        size: 0x0F6A,
        width: 320,
        height: 19,
        description: 'Landscape block F',
        paletteStrategy: 'single',
        paletteRefs: ['SCENE02.DAT@0x2F9B4'],
        paletteLayers: sameFile112('SCENE02.DAT', 0x2F9B4, LOW_BANK_BASE, 'SCENE02.DAT palette C'),
        paletteBase: LOW_BANK_BASE,
        pixelBase: LOW_BANK_PIXEL_BASE,
    }),
    entry({
        datFile: 'DATAA.DAT',
        offset: 0x00151,
        size: 0x0980,
        width: 320,
        height: 200,
        filename: 'ACCO.LZ',
        description: 'Accolade startup screen',
        paletteStrategy: 'single',
        paletteRefs: ['DATAA.DAT@0x00000 (ACCOCOLR.BIN)'],
        paletteLayers: sameFile112('DATAA.DAT', 0x00000, HIGH_BANK_BASE, 'ACCOCOLR.BIN'),
        paletteBase: HIGH_BANK_BASE,
        pixelBase: HIGH_BANK_PIXEL_BASE,
    }),
    entry({
        datFile: 'DATAA.DAT',
        offset: 0x01AC2,
        size: 0x2CE7,
        width: 160,
        height: 100,
        filename: 'TITLE1.LZ',
        description: 'Intro still 1',
        paletteStrategy: 'single',
        paletteRefs: ['DATAA.DAT@0x01971 (TITLCOLR.BIN)'],
        paletteLayers: sameFile112('DATAA.DAT', 0x01971, LOW_BANK_BASE, 'TITLCOLR.BIN'),
        paletteBase: LOW_BANK_BASE,
        pixelBase: LOW_BANK_PIXEL_BASE,
    }),
    entry({
        datFile: 'DATAA.DAT',
        offset: 0x047AA,
        size: 0x2556,
        width: 160,
        height: 100,
        filename: 'TITLE2.LZ',
        description: 'Intro still 2',
        paletteStrategy: 'single',
        paletteRefs: ['DATAA.DAT@0x01971 (TITLCOLR.BIN)'],
        paletteLayers: sameFile112('DATAA.DAT', 0x01971, LOW_BANK_BASE, 'TITLCOLR.BIN'),
        paletteBase: LOW_BANK_BASE,
        pixelBase: LOW_BANK_PIXEL_BASE,
    }),
    entry({
        datFile: 'DATAA.DAT',
        offset: 0x06D01,
        size: 0x25AC,
        width: 240,
        height: 69,
        filename: 'TITLELET.LZ',
        description: 'Title text overlay',
        paletteStrategy: 'single',
        paletteRefs: ['DATAA.DAT@0x0EBFF (TITL2COL.BIN)'],
        paletteLayers: sameFile112('DATAA.DAT', 0x0EBFF, HIGH_BANK_BASE, 'TITL2COL.BIN'),
        paletteBase: HIGH_BANK_BASE,
        pixelBase: 0,
        status: 'guessed',
        guessReason: 'Guessed to use TITL2COL.BIN because it is loaded for the same title-screen sequence and these pixels already include high indices.',
    }),
    entry({
        datFile: 'DATAA.DAT',
        offset: 0x092AE,
        size: 0x08C2,
        width: 256,
        height: 19,
        filename: 'TITLEL2.LZ',
        description: 'Copyright text overlay',
        paletteStrategy: 'single',
        paletteRefs: ['DATAA.DAT@0x0EBFF (TITL2COL.BIN)'],
        paletteLayers: sameFile112('DATAA.DAT', 0x0EBFF, HIGH_BANK_BASE, 'TITL2COL.BIN'),
        paletteBase: HIGH_BANK_BASE,
        pixelBase: 0,
        status: 'guessed',
        guessReason: 'Guessed to use TITL2COL.BIN because it is loaded for the same title-screen sequence and these pixels already include high indices.',
    }),
    entry({
        datFile: 'DATAA.DAT',
        offset: 0x09B71,
        size: 0x3BE5,
        width: 320,
        height: 66,
        filename: 'TITLEANI.LZ',
        description: 'Title animation',
        paletteStrategy: 'single',
        paletteRefs: ['DATAA.DAT@0x0EBFF (TITL2COL.BIN)'],
        paletteLayers: sameFile112('DATAA.DAT', 0x0EBFF, HIGH_BANK_BASE, 'TITL2COL.BIN'),
        paletteBase: HIGH_BANK_BASE,
        pixelBase: 0,
        status: 'guessed',
        guessReason: 'Guessed to use TITL2COL.BIN because it is loaded immediately before this title-screen image group.',
    }),
    entry({
        datFile: 'DATAA.DAT',
        offset: 0x0D757,
        size: 0x14A7,
        width: 128,
        height: 54,
        filename: 'TITLECAR.LZ',
        description: 'Title car inset',
        paletteStrategy: 'single',
        paletteRefs: ['DATAA.DAT@0x0EBFF (TITL2COL.BIN)'],
        paletteLayers: sameFile112('DATAA.DAT', 0x0EBFF, HIGH_BANK_BASE, 'TITL2COL.BIN'),
        paletteBase: HIGH_BANK_BASE,
        pixelBase: 0,
        status: 'guessed',
        guessReason: 'Guessed to use TITL2COL.BIN because it is loaded for the same title-screen sequence.',
    }),
    entry({
        datFile: 'DATAA.DAT',
        offset: 0x0EEA1,
        size: 0x33D9,
        width: 320,
        height: 56,
        filename: 'CREDITA.LZ',
        description: 'Credits page A',
        paletteStrategy: 'single',
        paletteRefs: ['DATAA.DAT@0x0ED50 (CREDCOLR.BIN)'],
        paletteLayers: sameFile112('DATAA.DAT', 0x0ED50, LOW_BANK_BASE, 'CREDCOLR.BIN'),
        paletteBase: LOW_BANK_BASE,
        pixelBase: LOW_BANK_PIXEL_BASE,
    }),
    entry({
        datFile: 'DATAA.DAT',
        offset: 0x1227B,
        size: 0x38F7,
        width: 320,
        height: 65,
        filename: 'CREDITB.LZ',
        description: 'Credits page B',
        paletteStrategy: 'single',
        paletteRefs: ['DATAA.DAT@0x0ED50 (CREDCOLR.BIN)'],
        paletteLayers: sameFile112('DATAA.DAT', 0x0ED50, LOW_BANK_BASE, 'CREDCOLR.BIN'),
        paletteBase: LOW_BANK_BASE,
        pixelBase: LOW_BANK_PIXEL_BASE,
    }),
    entry({
        datFile: 'DATAA.DAT',
        offset: 0x15B73,
        size: 0x344E,
        width: 320,
        height: 65,
        filename: 'CREDITC.LZ',
        description: 'Credits page C',
        paletteStrategy: 'single',
        paletteRefs: ['DATAA.DAT@0x0ED50 (CREDCOLR.BIN)'],
        paletteLayers: sameFile112('DATAA.DAT', 0x0ED50, LOW_BANK_BASE, 'CREDCOLR.BIN'),
        paletteBase: LOW_BANK_BASE,
        pixelBase: LOW_BANK_PIXEL_BASE,
    }),
    entry({
        datFile: 'DATAA.DAT',
        offset: 0x18FC2,
        size: 0x0112,
        width: 152,
        height: 8,
        filename: 'COMPASS.LZ',
        description: 'Compass strip',
        paletteStrategy: 'single',
        paletteRefs: ['DATAC.DAT@0x00495 (OTWCOL.BIN)'],
        paletteLayers: sameFile112('DATAC.DAT', 0x00495, LOW_BANK_BASE, 'OTWCOL.BIN'),
        paletteBase: LOW_BANK_BASE,
        pixelBase: LOW_BANK_PIXEL_BASE,
        status: 'guessed',
        guessReason: 'Guessed to use OTWCOL.BIN because the resource name matches compass/outdoor palette usage.',
    }),
    entry({
        datFile: 'DATAA.DAT',
        offset: 0x190D5,
        size: 0x0373,
        width: 496,
        height: 32,
        filename: 'CHASE.LZ',
        description: 'Camera view arrows',
        paletteStrategy: 'default-vga',
        paletteRefs: ['default VGA palette'],
        status: 'guessed',
        guessReason: 'Resolution confirmed as 496x32; palette is still guessed as default VGA.',
    }),
    entry({
        datFile: 'DATAA.DAT',
        offset: 0x19449,
        size: 0x12D1,
        width: 320,
        height: 48,
        filename: 'WATER.LZ',
        description: 'Water effect',
        paletteStrategy: 'single',
        paletteRefs: ['DATAC.DAT@0x00495 (OTWCOL.BIN)'],
        paletteLayers: sameFile112('DATAC.DAT', 0x00495, LOW_BANK_BASE, 'OTWCOL.BIN'),
        paletteBase: LOW_BANK_BASE,
        pixelBase: LOW_BANK_PIXEL_BASE,
        status: 'guessed',
        guessReason: 'Resolution confirmed as 320x48; palette is still guessed as OTWCOL.BIN.',
    }),
    entry({
        datFile: 'DATAA.DAT',
        offset: 0x1A71B,
        size: 0x0F3D,
        width: 320,
        height: 48,
        filename: 'WATEREGA.LZ',
        description: 'Water effect variant',
        paletteStrategy: 'single',
        paletteRefs: ['DATAC.DAT@0x00495 (OTWCOL.BIN)'],
        paletteLayers: sameFile112('DATAC.DAT', 0x00495, LOW_BANK_BASE, 'OTWCOL.BIN'),
        paletteBase: LOW_BANK_BASE,
        pixelBase: LOW_BANK_PIXEL_BASE,
        status: 'guessed',
        guessReason: 'Resolution confirmed as 320x48; palette is still guessed as OTWCOL.BIN.',
    }),
    entry({
        datFile: 'DATAA.DAT',
        offset: 0x1B659,
        size: 0x1CFF,
        width: 320,
        height: 96,
        filename: 'BROKE.LZ',
        description: 'Broken windshield overlay',
        paletteStrategy: 'default-vga',
        paletteRefs: ['default VGA palette'],
        status: 'guessed',
        guessReason: 'Guessed as default VGA because the decoded pixels stay in a narrow low-index range.',
    }),
    entry({
        datFile: 'DATAA.DAT',
        offset: 0x1D359,
        size: 0x136C,
        width: 320,
        height: 96,
        filename: 'BROKEGA.LZ',
        description: 'Broken windshield overlay variant',
        paletteStrategy: 'default-vga',
        paletteRefs: ['default VGA palette'],
        status: 'guessed',
        guessReason: 'Guessed as default VGA because the decoded pixels stay entirely in the base palette range.',
    }),
    entry({
        datFile: 'DATAB.DAT',
        offset: 0x00151,
        size: 0x2F33,
        width: 320,
        height: 100,
        filename: 'COPA.LZ',
        description: 'Police image A',
        paletteStrategy: 'single',
        paletteRefs: ['DATAB.DAT@0x00000 (COPCOLR.BIN)'],
        paletteLayers: sameFile112('DATAB.DAT', 0x00000, HIGH_BANK_BASE, 'COPCOLR.BIN'),
        paletteBase: HIGH_BANK_BASE,
        pixelBase: HIGH_BANK_PIXEL_BASE,
    }),
    entry({
        datFile: 'DATAB.DAT',
        offset: 0x03085,
        size: 0x2B91,
        width: 320,
        height: 58,
        filename: 'COPB.LZ',
        description: 'Police image B',
        paletteStrategy: 'single',
        paletteRefs: ['DATAB.DAT@0x00000 (COPCOLR.BIN)'],
        paletteLayers: sameFile112('DATAB.DAT', 0x00000, HIGH_BANK_BASE, 'COPCOLR.BIN'),
        paletteBase: HIGH_BANK_BASE,
        pixelBase: HIGH_BANK_PIXEL_BASE,
    }),
    entry({
        datFile: 'DATAB.DAT',
        offset: 0x05C17,
        size: 0x1306,
        width: 128,
        height: 90,
        filename: 'COPSEQ.LZ',
        description: 'Police light animation strip',
        paletteStrategy: 'single',
        paletteRefs: ['DATAB.DAT@0x00000 (COPCOLR.BIN)'],
        paletteLayers: sameFile112('DATAB.DAT', 0x00000, HIGH_BANK_BASE, 'COPCOLR.BIN'),
        paletteBase: HIGH_BANK_BASE,
        pixelBase: HIGH_BANK_PIXEL_BASE,
    }),
    entry({
        datFile: 'DATAB.DAT',
        offset: 0x07338,
        size: 0x1BFA,
        width: 192,
        height: 144,
        filename: 'KEYS.LZ',
        description: 'Keys image',
        paletteStrategy: 'single',
        paletteRefs: ['DATAB.DAT@0x071E7 (KEYCOLR.BIN)'],
        paletteLayers: sameFile112('DATAB.DAT', 0x071E7, LOW_BANK_BASE, 'KEYCOLR.BIN'),
        paletteBase: LOW_BANK_BASE,
        pixelBase: LOW_BANK_PIXEL_BASE,
    }),
    entry({
        datFile: 'DATAB.DAT',
        offset: 0x0A4D1,
        size: 0x13EB,
        width: 320,
        height: 200,
        filename: 'SELECT.LZ',
        description: 'Selection background',
        paletteStrategy: 'single',
        paletteRefs: ['DATAC.DAT@0x00151 (DIFFCOLR.BIN)'],
        paletteLayers: sameFile112('DATAC.DAT', 0x00151, LOW_BANK_BASE, 'DIFFCOLR.BIN'),
        paletteBase: LOW_BANK_BASE,
        pixelBase: LOW_BANK_PIXEL_BASE,
    }),
    entry({
        datFile: 'DATAB.DAT',
        offset: 0x0B8BD,
        size: 0x34EF,
        width: 320,
        height: 56,
        filename: 'DIFFLEVA.LZ',
        description: 'Difficulty detail A',
        paletteStrategy: 'single',
        paletteRefs: ['DATAC.DAT@0x00151 (DIFFCOLR.BIN)'],
        paletteLayers: sameFile112('DATAC.DAT', 0x00151, LOW_BANK_BASE, 'DIFFCOLR.BIN'),
        paletteBase: LOW_BANK_BASE,
        pixelBase: LOW_BANK_PIXEL_BASE,
    }),
    entry({
        datFile: 'DATAB.DAT',
        offset: 0x0EDAD,
        size: 0x3411,
        width: 320,
        height: 65,
        filename: 'DIFFLEVB.LZ',
        description: 'Difficulty detail B',
        paletteStrategy: 'single',
        paletteRefs: ['DATAC.DAT@0x00151 (DIFFCOLR.BIN)'],
        paletteLayers: sameFile112('DATAC.DAT', 0x00151, LOW_BANK_BASE, 'DIFFCOLR.BIN'),
        paletteBase: LOW_BANK_BASE,
        pixelBase: LOW_BANK_PIXEL_BASE,
    }),
    entry({
        datFile: 'DATAB.DAT',
        offset: 0x121BF,
        size: 0x3254,
        width: 320,
        height: 65,
        filename: 'DIFFLEVC.LZ',
        description: 'Difficulty detail C',
        paletteStrategy: 'single',
        paletteRefs: ['DATAC.DAT@0x00151 (DIFFCOLR.BIN)'],
        paletteLayers: sameFile112('DATAC.DAT', 0x00151, LOW_BANK_BASE, 'DIFFCOLR.BIN'),
        paletteBase: LOW_BANK_BASE,
        pixelBase: LOW_BANK_PIXEL_BASE,
    }),
    entry({
        datFile: 'DATAB.DAT',
        offset: 0x15414,
        size: 0x0100,
        width: 112,
        height: 10,
        filename: 'SSBJ.LZ',
        description: 'Unknown image fragment',
        paletteStrategy: 'default-vga',
        paletteRefs: ['default VGA palette'],
        status: 'guessed',
        guessReason: 'Resolution confirmed as 112x10; palette is still guessed as default VGA.',
    }),
    entry({
        datFile: 'DATAB.DAT',
        offset: 0x15666,
        size: 0x31E2,
        width: 320,
        height: 67,
        filename: 'TOPSCORA.LZ',
        description: 'Top score panel A',
        paletteStrategy: 'single',
        paletteRefs: ['DATAB.DAT@0x15515 (TOPCOLR.BIN)'],
        paletteLayers: sameFile112('DATAB.DAT', 0x15515, HIGH_BANK_BASE, 'TOPCOLR.BIN'),
        paletteBase: HIGH_BANK_BASE,
        pixelBase: HIGH_BANK_PIXEL_BASE,
    }),
    entry({
        datFile: 'DATAB.DAT',
        offset: 0x18849,
        size: 0x3535,
        width: 320,
        height: 66,
        filename: 'TOPSCORB.LZ',
        description: 'Top score panel B',
        paletteStrategy: 'single',
        paletteRefs: ['DATAB.DAT@0x15515 (TOPCOLR.BIN)'],
        paletteLayers: sameFile112('DATAB.DAT', 0x15515, HIGH_BANK_BASE, 'TOPCOLR.BIN'),
        paletteBase: HIGH_BANK_BASE,
        pixelBase: HIGH_BANK_PIXEL_BASE,
    }),
    entry({
        datFile: 'DATAB.DAT',
        offset: 0x1BD7F,
        size: 0x2FAC,
        width: 320,
        height: 67,
        filename: 'TOPSCORC.LZ',
        description: 'Top score panel C',
        paletteStrategy: 'single',
        paletteRefs: ['DATAB.DAT@0x15515 (TOPCOLR.BIN)'],
        paletteLayers: sameFile112('DATAB.DAT', 0x15515, HIGH_BANK_BASE, 'TOPCOLR.BIN'),
        paletteBase: HIGH_BANK_BASE,
        pixelBase: HIGH_BANK_PIXEL_BASE,
    }),
    entry({
        datFile: 'DATAC.DAT',
        offset: 0x002A2,
        size: 0x00F7,
        width: 184,
        height: 5,
        filename: 'DETAIL1.LZ',
        description: 'HUD text strip (MPH)',
        paletteStrategy: 'default-vga',
        paletteRefs: ['default VGA palette'],
    }),
    entry({
        datFile: 'DATAC.DAT',
        offset: 0x0039A,
        size: 0x00FA,
        width: 184,
        height: 5,
        filename: 'DETAIL2.LZ',
        description: 'HUD text strip (KPH)',
        paletteStrategy: 'default-vga',
        paletteRefs: ['default VGA palette'],
    }),
    entry({
        datFile: 'DATAC.DAT',
        offset: 0x005E6,
        size: 0x0112,
        width: 152,
        height: 8,
        filename: 'COMPASS.LZ',
        description: 'Compass strip',
        paletteStrategy: 'default-vga',
        paletteRefs: ['default VGA palette'],
    }),
    ...carEntries('CCERV.DAT', 40, [
        [0x00303, 0x01B92, 'CCERV.ICN', 208, 83, 'SC', 'Car selection icon'],
        [0x01E95, 0x00491, 'CCERV.SIC', 72, 40, 'SIC', 'Small car icon'],
        [0x02326, 0x014C9, 'CCERV.BIC', 112, 83, 'SC', 'Large car info panel'],
        [0x037EF, 0x02296, 'CCERV.SID', 112, 117, 'SC', 'Side profile'],
        [0x05A85, 0x0059D, 'CCERV.ETC', 56, 72, 'COL', 'Interior detail'],
        [0x06022, 0x0054E, 'CCERV.TOP', 320, 16, 'COL', 'Dashboard top'],
        [0x06570, 0x015AE, 'CCERV1.BOT', 320, 44, 'COL', 'Dashboard bottom left'],
        [0x07B1E, 0x027B7, 'CCERV2.BOT', 320, 44, 'COL', 'Dashboard bottom right'],
        [0x0A2D5, 0x015CC, 'CCERVL.BOT', 168, 48, 'COL', 'Wheel left'],
        [0x0B8A1, 0x016C4, 'CCERVR.BOT', 168, 48, 'COL', 'Wheel right'],
        [0x0CF65, 0x00862, 'CCERVFL1.LZ', 208, 117, 'SC', 'Car fly-in frame 1'],
        [0x0D7C7, 0x00A8E, 'CCERVFL2.LZ', 208, 200, 'SC', 'Car fly-in frame 2'],
    ]),
    ...carEntries('CCNSX.DAT', 40, [
        [0x00303, 0x01E9F, 'CCNSX.ICN', 208, 83, 'SC', 'Car selection icon'],
        [0x021A2, 0x00446, 'CCNSX.SIC', 72, 40, 'SIC', 'Small car icon'],
        [0x025E8, 0x0142A, 'CCNSX.BIC', 112, 83, 'SC', 'Large car info panel'],
        [0x03A12, 0x01508, 'CCNSX.SID', 112, 116, 'SC', 'Side profile'],
        [0x04F1A, 0x00545, 'CCNSX.ETC', 56, 72, 'COL', 'Interior detail'],
        [0x0545F, 0x00654, 'CCNSX.TOP', 320, 16, 'COL', 'Dashboard top'],
        [0x05AB3, 0x01DC5, 'CCNSX1.BOT', 320, 44, 'COL', 'Dashboard bottom left'],
        [0x07878, 0x02088, 'CCNSX2.BOT', 320, 44, 'COL', 'Dashboard bottom right'],
        [0x09900, 0x01305, 'CCNSXL.BOT', 168, 48, 'COL', 'Wheel left'],
        [0x0AC05, 0x01317, 'CCNSXR.BOT', 168, 48, 'COL', 'Wheel right'],
        [0x0BF1C, 0x007E9, 'CCNSXFL1.LZ', 208, 117, 'SC', 'Car fly-in frame 1'],
        [0x0C705, 0x008D6, 'CCNSXFL2.LZ', 208, 200, 'SC', 'Car fly-in frame 2'],
    ]),
    ...carEntries('CDIAB.DAT', 40, [
        [0x00303, 0x02533, 'CDIAB.ICN', 208, 83, 'SC', 'Car selection icon'],
        [0x02836, 0x00363, 'CDIAB.SIC', 72, 40, 'SIC', 'Small car icon'],
        [0x02B99, 0x00CF0, 'CDIAB.BIC', 112, 83, 'SC', 'Large car info panel'],
        [0x03889, 0x01BE6, 'CDIAB.SID', 112, 116, 'SC', 'Side profile'],
        [0x0546F, 0x00433, 'CDIAB.ETC', 56, 72, 'COL', 'Interior detail'],
        [0x058A2, 0x00474, 'CDIAB.TOP', 320, 16, 'COL', 'Dashboard top'],
        [0x05D16, 0x01292, 'CDIAB1.BOT', 320, 44, 'COL', 'Dashboard bottom left'],
        [0x06FA8, 0x019EE, 'CDIAB2.BOT', 320, 44, 'COL', 'Dashboard bottom right'],
        [0x08996, 0x0107F, 'CDIABL.BOT', 168, 48, 'COL', 'Wheel left'],
        [0x09A15, 0x01103, 'CDIABR.BOT', 168, 48, 'COL', 'Wheel right'],
        [0x0AB18, 0x00855, 'CDIABFL1.LZ', 208, 117, 'SC', 'Car fly-in frame 1'],
        [0x0B36D, 0x008DF, 'CDIABFL2.LZ', 208, 200, 'SC', 'Car fly-in frame 2'],
    ]),
    ...carEntries('CMYTH.DAT', 47, [
        [0x00303, 0x02472, 'CMYTH.ICN', 208, 83, 'SC', 'Car selection icon'],
        [0x02775, 0x00463, 'CMYTH.SIC', 72, 47, 'SIC', 'Small car icon'],
        [0x02BD8, 0x01800, 'CMYTH.BIC', 112, 83, 'SC', 'Large car info panel'],
        [0x043D8, 0x02008, 'CMYTH.SID', 112, 116, 'SC', 'Side profile'],
        [0x063E0, 0x004B0, 'CMYTH.ETC', 56, 72, 'COL', 'Interior detail'],
        [0x06890, 0x00536, 'CMYTH.TOP', 320, 16, 'COL', 'Dashboard top'],
        [0x06DC6, 0x01EC1, 'CMYTH1.BOT', 320, 44, 'COL', 'Dashboard bottom left'],
        [0x08C87, 0x023B8, 'CMYTH2.BOT', 320, 44, 'COL', 'Dashboard bottom right'],
        [0x0B03F, 0x014EB, 'CMYTHL.BOT', 168, 48, 'COL', 'Wheel left'],
        [0x0C52A, 0x014C0, 'CMYTHR.BOT', 168, 48, 'COL', 'Wheel right'],
        [0x0D9EA, 0x00815, 'CMYTHFL1.LZ', 208, 117, 'SC', 'Car fly-in frame 1'],
        [0x0E1FF, 0x008AE, 'CMYTHFL2.LZ', 208, 200, 'SC', 'Car fly-in frame 2'],
    ]),
    ...carEntries('CSTEL.DAT', 40, [
        [0x00303, 0x01D4A, 'CSTEL.ICN', 208, 83, 'SC', 'Car selection icon'],
        [0x0204D, 0x004E5, 'CSTEL.SIC', 72, 40, 'SIC', 'Small car icon'],
        [0x02532, 0x0124D, 'CSTEL.BIC', 112, 83, 'SC', 'Large car info panel'],
        [0x0377F, 0x014C7, 'CSTEL.SID', 112, 116, 'SC', 'Side profile'],
        [0x04C46, 0x00567, 'CSTEL.ETC', 56, 72, 'COL', 'Interior detail'],
        [0x051AD, 0x004F9, 'CSTEL.TOP', 320, 16, 'COL', 'Dashboard top'],
        [0x056A6, 0x01C30, 'CSTEL1.BOT', 320, 44, 'COL', 'Dashboard bottom left'],
        [0x072D6, 0x021F3, 'CSTEL2.BOT', 320, 44, 'COL', 'Dashboard bottom right'],
        [0x094C9, 0x012A1, 'CSTELL.BOT', 168, 48, 'COL', 'Wheel left'],
        [0x0A76A, 0x012D1, 'CSTELR.BOT', 168, 48, 'COL', 'Wheel right'],
        [0x0BA3B, 0x008DA, 'CSTELFL1.LZ', 208, 117, 'SC', 'Car fly-in frame 1'],
        [0x0C315, 0x0083A, 'CSTELFL2.LZ', 208, 200, 'SC', 'Car fly-in frame 2'],
    ]),
];
