; +-------------------------------------------------------------------------+
seg000:0000 ; ¦     This file is generated by The Interactive Disassembler (IDA)        ¦
seg000:0000 ; ¦     Copyright (c) 2010 by Hex-Rays SA, <support@hex-rays.com>           ¦
seg000:0000 ; ¦                      Licensed to: Freeware version                      ¦
seg000:0000 ; +-------------------------------------------------------------------------+
seg000:0000 ;
seg000:0000 ; Input MD5   : 765B73E95B017634AE9FDE8688831045
seg000:0000
seg000:0000 ; File Name   : Z:\home\sebastian\projects\td3\td3_unpacked\TD3.unpacked.EXE
seg000:0000 ; Format      : MS-DOS executable (EXE)
seg000:0000 ; Base Address: 0h Range: 0h-2EB8Eh Loaded length: 2BF40h
seg000:0000 ; Entry Point : 18E6:1A
seg000:0000
seg000:0000
seg000:0000 unicode         macro page,string,zero
seg000:0000                 irpc c,<string>
seg000:0000                 db '&c', page
seg000:0000                 endm
seg000:0000                 ifnb <zero>
seg000:0000                 dw zero
seg000:0000                 endif
seg000:0000 endm
seg000:0000
seg000:0000                 .386
seg000:0000                 .model large
seg000:0000
seg000:0000 ; ---------------------------------------------------------------------------
seg000:0000
seg000:0000 ; Segment type: Pure code
seg000:0000 seg000          segment byte public 'CODE' use16
seg000:0000                 assume cs:seg000
seg000:0000                 assume es:nothing, ss:nothing, ds:dseg, fs:nothing, gs:nothing
seg000:0000
seg000:0000 ; ¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦ S U B R O U T I N E ¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦
seg000:0000
seg000:0000 ; Attributes: bp-based frame
seg000:0000
seg000:0000 sub_0           proc near               ; CODE XREF: start+97␙P
seg000:0000
seg000:0000 var_12          = word ptr -12h
seg000:0000 var_10          = word ptr -10h
seg000:0000 var_E           = word ptr -0Eh
seg000:0000 var_C           = word ptr -0Ch
seg000:0000 var_A           = word ptr -0Ah
seg000:0000 var_8           = word ptr -8
seg000:0000 var_6           = word ptr -6
seg000:0000 var_4           = word ptr -4
seg000:0000 var_2           = word ptr -2
seg000:0000
seg000:0000                 push    bp
seg000:0001                 mov     bp, sp
seg000:0003                 sub     sp, 12h
seg000:0006                 push    di
seg000:0007                 push    si
seg000:0008                 sub     ax, ax
seg000:000A                 mov     word_1F166, ax
seg000:000D                 mov     byte_1F168, al
seg000:0010                 mov     byte_1F16C, al
seg000:0013                 mov     byte_1F17E, al
seg000:0016                 mov     byte_280CC, al
seg000:0019                 mov     ax, 4Fh ; 'O'
seg000:001C                 push    ax
seg000:001D                 mov     ax, 0E998h
seg000:0020                 push    ax
seg000:0021                 call    sub_19680
seg000:0026                 add     sp, 4
seg000:0029                 mov     al, byte_2DA78
seg000:002C                 and     al, 0DFh
seg000:002E                 mov     byte_209D6, al
seg000:0031                 mov     byte_1FB6A, al
seg000:0034                 mov     byte_1FBBA, al
seg000:0037                 mov     byte_1FBAA, al
seg000:003A                 mov     byte_1FB9A, al
seg000:003D                 mov     byte_1FB8A, al
seg000:0040                 mov     byte_1FB7A, al
seg000:0043                 mov     byte_20FA5, al
seg000:0046                 mov     byte_1F1BA, al
seg000:0049                 mov     byte_209F7, al
seg000:004C                 mov     byte_20AD7, al
seg000:004F                 mov     word_1F166, 0FFh
seg000:0055                 push    cs
seg000:0056                 call    near ptr sub_8DC
seg000:0059                 call    sub_39D6
seg000:005E                 call    sub_CD55
seg000:0063                 call    sub_3A2A
seg000:0068                 push    cs
seg000:0069                 call    near ptr sub_10D4
seg000:006C                 call    sub_10203
seg000:0071                 push    seg_1F1B8
seg000:0075                 push    word_1F1B6
seg000:0079                 call    sub_1974A
seg000:007E                 add     sp, 4
seg000:0081                 mov     ax, 42h ; 'B'
seg000:0084                 push    ax
seg000:0085                 mov     ax, 0A9Ch
seg000:0088                 push    ax
seg000:0089                 call    sub_195EA
seg000:008E                 add     sp, 4
seg000:0091                 push    word_2D8AE
seg000:0095                 push    word_2D8AC
seg000:0099                 mov     ax, 0A9Ah
seg000:009C                 push    ax
seg000:009D                 push    cs
seg000:009E                 call    near ptr sub_E26
seg000:00A1                 add     sp, 6
seg000:00A4                 cmp     word_2D628, 13h
seg000:00A9                 jnz     short loc_B0
seg000:00AB                 mov     ax, 4Dh ; 'M'
seg000:00AE                 jmp     short loc_B3
seg000:00B0 ; ---------------------------------------------------------------------------
seg000:00B0
seg000:00B0 loc_B0:                                 ; CODE XREF: sub_0+A9␘j
seg000:00B0                 mov     ax, 56h ; 'V'
seg000:00B3
seg000:00B3 loc_B3:                                 ; CODE XREF: sub_0+AE␘j
seg000:00B3                 push    ax
seg000:00B4                 mov     ax, 0A9Ch
seg000:00B7                 push    ax
seg000:00B8                 call    sub_195EA
seg000:00BD                 add     sp, 4
seg000:00C0                 push    word_2D842
seg000:00C4                 push    word_2D840
seg000:00C8                 mov     ax, 0A9Ah
seg000:00CB                 push    ax
seg000:00CC                 push    cs
seg000:00CD                 call    near ptr sub_E26
seg000:00D0                 add     sp, 6
seg000:00D3                 mov     ax, 62h ; 'b'
seg000:00D6                 push    ax
seg000:00D7                 mov     ax, 0A9Ch
seg000:00DA                 push    ax
seg000:00DB                 call    sub_195EA
seg000:00E0                 add     sp, 4
seg000:00E3                 push    word_2C18A
seg000:00E7                 push    word_2C188
seg000:00EB                 mov     ax, 0A9Ah
seg000:00EE                 push    ax
seg000:00EF                 push    cs
seg000:00F0                 call    near ptr sub_E26
seg000:00F3                 add     sp, 6
seg000:00F6                 cmp     word_2D628, 13h
seg000:00FB                 jnz     short loc_102
seg000:00FD                 mov     ax, 6Bh ; 'k'
seg000:0100                 jmp     short loc_105
seg000:0102 ; ---------------------------------------------------------------------------
seg000:0102
seg000:0102 loc_102:                                ; CODE XREF: sub_0+FB␘j
seg000:0102                 mov     ax, 74h ; 't'
seg000:0105
seg000:0105 loc_105:                                ; CODE XREF: sub_0+100␘j
seg000:0105                 push    ax
seg000:0106                 mov     ax, 0A9Ch
seg000:0109                 push    ax
seg000:010A                 call    sub_195EA
seg000:010F                 add     sp, 4
seg000:0112                 push    word_2D84C
seg000:0116                 push    word_2D84A
seg000:011A                 mov     ax, 0A9Ah
seg000:011D                 push    ax
seg000:011E                 push    cs
seg000:011F                 call    near ptr sub_E26
seg000:0122                 add     sp, 6
seg000:0125                 mov     word_1F166, 1
seg000:012B                 jmp     short loc_150
seg000:012B ; ---------------------------------------------------------------------------
seg000:012D                 align 2
seg000:012E
seg000:012E loc_12E:                                ; CODE XREF: sub_0+156␙j
seg000:012E                 cmp     ax, 2
seg000:0131                 jz      short loc_176
seg000:0133                 cmp     ax, 3
seg000:0136                 jz      short loc_190
seg000:0138                 cmp     ax, 4
seg000:013B                 jz      short loc_1A6
seg000:013D                 cmp     ax, 5
seg000:0140                 jnz     short loc_145
seg000:0142                 jmp     loc_21E
seg000:0145 ; ---------------------------------------------------------------------------
seg000:0145
seg000:0145 loc_145:                                ; CODE XREF: sub_0+140␘j
seg000:0145                 cmp     ax, 6
seg000:0148                 jnz     short loc_150
seg000:014A
seg000:014A loc_14A:                                ; CODE XREF: sub_0+16C␙j
seg000:014A                                         ; sub_0+173␙j ...
seg000:014A                 mov     word_1F166, 4
seg000:0150
seg000:0150 loc_150:                                ; CODE XREF: sub_0+12B␘j
seg000:0150                                         ; sub_0+148␘j ...
seg000:0150                 mov     ax, word_1F166
seg000:0153                 cmp     ax, 1
seg000:0156                 jnz     short loc_12E
seg000:0158                 call    sub_1DAA
seg000:015D                 call    sub_70AE
seg000:0162                 call    sub_45D0
seg000:0167                 mov     [bp+var_C], ax
seg000:016A                 or      ax, ax
seg000:016C                 jz      short loc_14A
seg000:016E                 call    sub_4438
seg000:0173                 jmp     short loc_14A
seg000:0173 ; ---------------------------------------------------------------------------
seg000:0175                 align 2
seg000:0176
seg000:0176 loc_176:                                ; CODE XREF: sub_0+131␘j
seg000:0176                 call    sub_3BFC
seg000:017B                 mov     [bp+var_C], ax
seg000:017E                 or      ax, ax
seg000:0180                 jnz     short loc_187
seg000:0182                 mov     byte_1F168, 1
seg000:0187
seg000:0187 loc_187:                                ; CODE XREF: sub_0+180␘j
seg000:0187                 mov     word_1F166, 5
seg000:018D                 jmp     short loc_150
seg000:018D ; ---------------------------------------------------------------------------
seg000:018F                 align 2
seg000:0190
seg000:0190 loc_190:                                ; CODE XREF: sub_0+136␘j
seg000:0190                 mov     ax, word_20FAF
seg000:0193                 or      ax, word_20FB1
seg000:0197                 jz      short loc_14A
seg000:0199                 sub     ax, ax
seg000:019B                 push    ax
seg000:019C                 call    sub_2C88
seg000:01A1                 add     sp, 2
seg000:01A4                 jmp     short loc_14A
seg000:01A6 ; ---------------------------------------------------------------------------
seg000:01A6
seg000:01A6 loc_1A6:                                ; CODE XREF: sub_0+13B␘j
seg000:01A6                 call    sub_70AE
seg000:01AB                 mov     al, byte_2A6B6
seg000:01AE                 sub     ah, ah
seg000:01B0                 push    ax
seg000:01B1                 call    sub_3A5C
seg000:01B6                 add     sp, 2
seg000:01B9
seg000:01B9 loc_1B9:                                ; CODE XREF: sub_0+204␙j
seg000:01B9                                         ; sub_0+213␙j ...
seg000:01B9                 cmp     word_1F166, 4
seg000:01BE                 jnz     short loc_150
seg000:01C0                 sub     al, al
seg000:01C2                 mov     byte_1FBEA, al
seg000:01C5                 sub     ah, ah
seg000:01C7                 mov     word_2D89C, ax
seg000:01CA                 call    sub_3186
seg000:01CF                 cmp     word_2D89C, 4
seg000:01D4                 jnz     short loc_1DB
seg000:01D6                 call    sub_4438
seg000:01DB
seg000:01DB loc_1DB:                                ; CODE XREF: sub_0+1D4␘j
seg000:01DB                 cmp     word_2D89C, 3
seg000:01E0                 jnz     short loc_1E7
seg000:01E2                 call    sub_5340
seg000:01E7
seg000:01E7 loc_1E7:                                ; CODE XREF: sub_0+1E0␘j
seg000:01E7                 cmp     word_2D89C, 2
seg000:01EC                 jnz     short loc_1F3
seg000:01EE                 call    sub_4E16
seg000:01F3
seg000:01F3 loc_1F3:                                ; CODE XREF: sub_0+1EC␘j
seg000:01F3                 cmp     word_2D89C, 1
seg000:01F8                 jnz     short loc_1FF
seg000:01FA                 call    sub_5838
seg000:01FF
seg000:01FF loc_1FF:                                ; CODE XREF: sub_0+1F8␘j
seg000:01FF                 cmp     word_2D89C, 0
seg000:0204                 jnz     short loc_1B9
seg000:0206                 cmp     byte_1F168, 0
seg000:020B                 jnz     short loc_216
seg000:020D                 mov     word_1F166, 2
seg000:0213                 jmp     short loc_1B9
seg000:0213 ; ---------------------------------------------------------------------------
seg000:0215                 align 2
seg000:0216
seg000:0216 loc_216:                                ; CODE XREF: sub_0+20B␘j
seg000:0216                 mov     word_1F166, 5
seg000:021C                 jmp     short loc_1B9
seg000:021E ; ---------------------------------------------------------------------------
seg000:021E
seg000:021E loc_21E:                                ; CODE XREF: sub_0+142␘j
seg000:021E                 call    sub_4534
seg000:0223                 sub     al, al
seg000:0225                 mov     byte_1FBEA, al
seg000:0228                 sub     ah, ah
seg000:022A                 mov     [bp+var_E], ax
seg000:022D                 mov     byte_1F174, 1
seg000:0232                 cmp     word_1FBE4, 3
seg000:0237                 jl      short loc_23C
seg000:0239                 mov     byte_1F174, al
seg000:023C
seg000:023C loc_23C:                                ; CODE XREF: sub_0+237␘j
seg000:023C                 mov     [bp+var_C], 0
seg000:0241                 jmp     short loc_254
seg000:0241 ; ---------------------------------------------------------------------------
seg000:0243                 align 2
seg000:0244
seg000:0244 loc_244:                                ; CODE XREF: sub_0+280␙j
seg000:0244                 mov     ax, 1Bh
seg000:0247                 imul    [bp+var_C]
seg000:024A                 mov     bx, ax
seg000:024C                 mov     byte ptr [bx-15E4h], 5
seg000:0251
seg000:0251 loc_251:                                ; CODE XREF: sub_0+28F␙j
seg000:0251                 inc     [bp+var_C]
seg000:0254
seg000:0254 loc_254:                                ; CODE XREF: sub_0+241␘j
seg000:0254                 cmp     [bp+var_C], 4
seg000:0258                 jl      short loc_25D
seg000:025A                 jmp     loc_73E
seg000:025D ; ---------------------------------------------------------------------------
seg000:025D
seg000:025D loc_25D:                                ; CODE XREF: sub_0+258␘j
seg000:025D                 mov     [bp+var_2], 0
seg000:0262
seg000:0262 loc_262:                                ; CODE XREF: sub_0+279␙j
seg000:0262                 mov     ax, 1Bh
seg000:0265                 imul    [bp+var_C]
seg000:0268                 mov     si, ax
seg000:026A                 mov     bx, [bp+var_2]
seg000:026D                 mov     byte ptr [bx+si-15FCh], 0
seg000:0272                 inc     [bp+var_2]
seg000:0275                 cmp     [bp+var_2], 1Bh
seg000:0279                 jl      short loc_262
seg000:027B                 cmp     byte_1F168, 1
seg000:0280                 jz      short loc_244
seg000:0282                 mov     ax, 1Bh
seg000:0285                 imul    [bp+var_C]
seg000:0288                 mov     bx, ax
seg000:028A                 mov     byte ptr [bx-15E4h], 1
seg000:028F                 jmp     short loc_251
seg000:028F ; ---------------------------------------------------------------------------
seg000:0291                 align 2
seg000:0292
seg000:0292 loc_292:                                ; CODE XREF: sub_0+747␙j
seg000:0292                 mov     [bp+var_C], 0
seg000:0297                 jmp     short loc_2B9
seg000:0297 ; ---------------------------------------------------------------------------
seg000:0299                 align 2
seg000:029A
seg000:029A loc_29A:                                ; CODE XREF: sub_0+2B3␙j
seg000:029A                 inc     [bp+var_2]
seg000:029D
seg000:029D loc_29D:                                ; CODE XREF: sub_0+2C4␙j
seg000:029D                 cmp     [bp+var_2], 0Ah
seg000:02A1                 jge     short loc_2B6
seg000:02A3                 mov     ax, 1Bh
seg000:02A6                 imul    [bp+var_C]
seg000:02A9                 mov     si, ax
seg000:02AB                 mov     bx, [bp+var_2]
seg000:02AE                 mov     byte ptr [bx+si-15FCh], 0
seg000:02B3                 jmp     short loc_29A
seg000:02B3 ; ---------------------------------------------------------------------------
seg000:02B5                 align 2
seg000:02B6
seg000:02B6 loc_2B6:                                ; CODE XREF: sub_0+2A1␘j
seg000:02B6                 inc     [bp+var_C]
seg000:02B9
seg000:02B9 loc_2B9:                                ; CODE XREF: sub_0+297␘j
seg000:02B9                 cmp     [bp+var_C], 4
seg000:02BD                 jge     short loc_2C6
seg000:02BF                 mov     [bp+var_2], 0
seg000:02C4                 jmp     short loc_29D
seg000:02C6 ; ---------------------------------------------------------------------------
seg000:02C6
seg000:02C6 loc_2C6:                                ; CODE XREF: sub_0+2BD␘j
seg000:02C6                 mov     byte_1FAA4, 1
seg000:02CB                 jmp     loc_6C8
seg000:02CE ; ---------------------------------------------------------------------------
seg000:02CE
seg000:02CE loc_2CE:                                ; CODE XREF: sub_0+72A␙j
seg000:02CE                 mov     ah, byte_2C198
seg000:02D2                 sub     al, al
seg000:02D4                 sub     dx, dx
seg000:02D6                 mov     cx, 3Ch ; '<'
seg000:02D9                 div     cx
seg000:02DB                 mov     ch, byte_2D84E
seg000:02DF                 sub     cl, cl
seg000:02E1                 add     ax, cx
seg000:02E3                 mov     [bp+var_6], ax
seg000:02E6                 mov     [bp+var_4], 0
seg000:02EB                 mov     dx, [bp+var_4]
seg000:02EE                 mov     cx, ax
seg000:02F0                 mov     bx, dx
seg000:02F2                 shl     ax, 1
seg000:02F4                 rcl     dx, 1
seg000:02F6                 shl     ax, 1
seg000:02F8                 rcl     dx, 1
seg000:02FA                 add     ax, cx
seg000:02FC                 adc     dx, bx
seg000:02FE                 mov     cl, 3
seg000:0300
seg000:0300 loc_300:                                ; CODE XREF: sub_0+306␙j
seg000:0300                 shr     dx, 1
seg000:0302                 rcr     ax, 1
seg000:0304                 dec     cl
seg000:0306                 jnz     short loc_300
seg000:0308                 mov     [bp+var_6], ax
seg000:030B                 mov     [bp+var_4], dx
seg000:030E                 mov     al, ah
seg000:0310                 mov     ah, dl
seg000:0312                 mov     dl, dh
seg000:0314                 sub     dh, dh
seg000:0316                 mov     byte_1FAAE, al
seg000:0319                 mov     ax, 3Ch ; '<'
seg000:031C                 cwd
seg000:031D                 push    dx
seg000:031E                 push    ax
seg000:031F                 mov     al, byte ptr [bp+var_6]
seg000:0322                 sub     ah, ah
seg000:0324                 sub     cx, cx
seg000:0326                 push    cx
seg000:0327                 push    ax
seg000:0328                 call    sub_1983C
seg000:032D                 mov     al, ah
seg000:032F                 mov     ah, dl
seg000:0331                 mov     dl, dh
seg000:0333                 sub     dh, dh
seg000:0335
seg000:0335 loc_335:                                ; CODE XREF: sub_0+736␙j
seg000:0335                 mov     byte_1FAAF, al
seg000:0338                 mov     ax, 3Ch ; '<'
seg000:033B                 cwd
seg000:033C                 push    dx
seg000:033D                 push    ax
seg000:033E                 mov     al, byte_1FAAE
seg000:0341                 sub     ah, ah
seg000:0343                 sub     cx, cx
seg000:0345                 push    cx
seg000:0346                 push    ax
seg000:0347                 call    sub_1983C
seg000:034C                 mov     cl, byte_1FAAF
seg000:0350                 sub     ch, ch
seg000:0352                 add     ax, cx
seg000:0354                 adc     dx, 0
seg000:0357                 mov     [bp+var_6], ax
seg000:035A                 mov     [bp+var_4], dx
seg000:035D                 mov     ax, 1770h
seg000:0360                 cwd
seg000:0361                 push    dx
seg000:0362                 push    ax
seg000:0363                 mov     al, byte_1FAA6
seg000:0366                 sub     ah, ah
seg000:0368                 sub     cx, cx
seg000:036A                 push    cx
seg000:036B                 push    ax
seg000:036C                 call    sub_1983C
seg000:0371                 mov     cx, 64h ; 'd'
seg000:0374                 sub     bx, bx
seg000:0376                 push    bx
seg000:0377                 push    cx
seg000:0378                 mov     cl, byte_1FAA7
seg000:037C                 sub     ch, ch
seg000:037E                 push    bx
seg000:037F                 push    cx
seg000:0380                 mov     si, ax
seg000:0382                 mov     di, dx
seg000:0384                 call    sub_1983C
seg000:0389                 mov     cl, byte_1FAA8
seg000:038D                 sub     ch, ch
seg000:038F                 sub     bx, bx
seg000:0391                 mov     [bp+var_12], ax
seg000:0394                 mov     [bp+var_10], dx
seg000:0397                 mov     ax, cx
seg000:0399                 mov     dx, bx
seg000:039B                 shl     cx, 1
seg000:039D                 rcl     bx, 1
seg000:039F                 shl     cx, 1
seg000:03A1                 rcl     bx, 1
seg000:03A3                 add     cx, ax
seg000:03A5                 adc     bx, dx
seg000:03A7                 shl     cx, 1
seg000:03A9                 rcl     bx, 1
seg000:03AB                 add     cx, [bp+var_12]
seg000:03AE                 adc     bx, [bp+var_10]
seg000:03B1                 add     cx, si
seg000:03B3                 adc     bx, di
seg000:03B5                 mov     [bp+var_A], cx
seg000:03B8                 mov     [bp+var_8], bx
seg000:03BB                 mov     ax, cx
seg000:03BD                 or      ax, bx
seg000:03BF                 jz      short loc_3E0
seg000:03C1                 push    bx
seg000:03C2                 push    cx
seg000:03C3                 mov     ax, 1770h       ; DATA XREF: sub_D632+13␙o
seg000:03C6                 cwd
seg000:03C7                 push    dx
seg000:03C8                 push    ax
seg000:03C9                 push    [bp+var_4]
seg000:03CC                 push    [bp+var_6]
seg000:03CF                 call    sub_1983C
seg000:03D4                 push    dx
seg000:03D5                 push    ax
seg000:03D6                 call    sub_197A0
seg000:03DB                 mov     byte_1FAA9, al
seg000:03DE                 jmp     short loc_3E5
seg000:03E0 ; ---------------------------------------------------------------------------
seg000:03E0
seg000:03E0 loc_3E0:                                ; CODE XREF: sub_0+3BF␘j
seg000:03E0                 mov     byte_1FAA9, 0
seg000:03E5
seg000:03E5 loc_3E5:                                ; CODE XREF: sub_0+3DE␘j
seg000:03E5                 mov     al, byte_1FAA9
seg000:03E8                 sub     ah, ah
seg000:03EA                 mov     cx, ax
seg000:03EC                 mov     ax, word_1FBE4
seg000:03EF                 add     ax, 4
seg000:03F2                 mul     cx
seg000:03F4                 mov     [bp+var_A], ax
seg000:03F7                 mov     [bp+var_8], 0
seg000:03FC                 mov     ax, [bp+var_6]
seg000:03FF                 or      ax, [bp+var_4]
seg000:0402                 jz      short loc_42E
seg000:0404                 cmp     byte_1FABE, 0
seg000:0409                 jz      short loc_42E
seg000:040B                 push    [bp+var_4]
seg000:040E                 push    [bp+var_6]      ; DATA XREF: sub_168A2:loc_16903␙r
seg000:040E                                         ; seg032:09E3␙r
seg000:0411                 mov     ax, 14h
seg000:0414                 cwd
seg000:0415                 push    dx
seg000:0416                 push    ax
seg000:0417
seg000:0417 loc_417:                                ; DATA XREF: sub_CD55+7␙r
seg000:0417                                         ; sub_CD55+F␙w ...
seg000:0417                 sub     ax, ax
seg000:0419                 push    ax
seg000:041A                 push    word_285A7
seg000:041E                 push    [bp+var_8]
seg000:0421                 push    [bp+var_A]
seg000:0424                 call    sub_1983C
seg000:0429                 push    dx
seg000:042A                 push    ax
seg000:042B                 jmp     short loc_45C
seg000:042B ; ---------------------------------------------------------------------------
seg000:042D                 align 2
seg000:042E
seg000:042E loc_42E:                                ; CODE XREF: sub_0+402␘j
seg000:042E                                         ; sub_0+409␘j
seg000:042E                 mov     ax, word_285A7
seg000:0431                 sub     dx, dx
seg000:0433                 cmp     [bp+var_4], dx
seg000:0436                 jb      short loc_44A
seg000:0438                 ja      short loc_43F
seg000:043A                 cmp     [bp+var_6], ax
seg000:043D                 jbe     short loc_44A
seg000:043F
seg000:043F loc_43F:                                ; CODE XREF: sub_0+438␘j
seg000:043F                 mov     ax, word_285A7
seg000:0442                 mov     [bp+var_6], ax
seg000:0445                 mov     [bp+var_4], 0
seg000:044A
seg000:044A loc_44A:                                ; CODE XREF: sub_0+436␘j
seg000:044A                                         ; sub_0+43D␘j
seg000:044A                 mov     ax, 60h ; '`'
seg000:044D                 cwd
seg000:044E
seg000:044E loc_44E:                                ; DATA XREF: seg020:0093␙w
seg000:044E                 push    dx
seg000:044F                 push    ax
seg000:0450                 push    [bp+var_8]
seg000:0453                 push    [bp+var_A]
seg000:0456                 push    [bp+var_4]
seg000:0459                 push    [bp+var_6]
seg000:045C
seg000:045C loc_45C:                                ; CODE XREF: sub_0+42B␘j
seg000:045C                 call    sub_1983C
seg000:0461                 push    dx
seg000:0462                 push    ax
seg000:0463
seg000:0463 loc_463:                                ; DATA XREF: seg020:0098␙r
seg000:0463                                         ; sub_1B5D7+36␙r
seg000:0463                 call    sub_198B8
seg000:0468                 mov     word_1F160, ax
seg000:046B                 mov     word_1F162, dx
seg000:046F                 cmp     dx, 0Fh
seg000:0472                 jb      short loc_487
seg000:0474                 ja      short loc_47B
seg000:0476                 cmp     ax, 4240h
seg000:0479                 jbe     short loc_487
seg000:047B
seg000:047B loc_47B:                                ; CODE XREF: sub_0+474␘j
seg000:047B                 mov     word_1F160, 4240h
seg000:0481                 mov     word_1F162, 0Fh
seg000:0487
seg000:0487 loc_487:                                ; CODE XREF: sub_0+472␘j
seg000:0487                                         ; sub_0+479␘j
seg000:0487                                         ; DATA XREF: ...
seg000:0487                 mov     al, byte ptr word_1F160
seg000:048A                 mov     byte_1FAAA, al
seg000:048D                 mov     ax, word_1F160
seg000:0490                 mov     dx, word_1F162
seg000:0494                 mov     al, ah
seg000:0496                 mov     ah, dl          ; DATA XREF: seg005:0ED2␙w
seg000:0496                                         ; seg005:0ED8␙w
seg000:0498                 mov     dl, dh
seg000:049A                 sub     dh, dh
seg000:049C                 mov     byte_1FAAB, al
seg000:049F                 mov     al, byte ptr word_1F162
seg000:04A2                 mov     byte_1FAAC, al
seg000:04A5                 mov     ax, word_1F160
seg000:04A8                 mov     dx, word_1F162
seg000:04AC                 mov     cl, 18h
seg000:04AE
seg000:04AE loc_4AE:                                ; CODE XREF: sub_0+4B4␙j
seg000:04AE                 shr     dx, 1
seg000:04B0                 rcr     ax, 1
seg000:04B2                 dec     cl
seg000:04B4                 jnz     short loc_4AE
seg000:04B6                 mov     byte_1FAAD, al
seg000:04B9                 mov     word_1F166, 6
seg000:04BF                 mov     ax, word_1F160
seg000:04C2                 mov     dx, word_1F162
seg000:04C6                 add     word_1FABA, ax
seg000:04CA                 adc     word_1FABC, dx
seg000:04CE                 mov     al, byte_2A6F4
seg000:04D1                 add     byte_1FAB2, al
seg000:04D5                 cmp     byte_1FAB2, 9
seg000:04DA                 jbe     short loc_4E5
seg000:04DC                 sub     byte_1FAB2, 0Ah
seg000:04E1                 inc     byte_1FAB1
seg000:04E5
seg000:04E5 loc_4E5:                                ; CODE XREF: sub_0+4DA␘j
seg000:04E5                 mov     al, byte_2A6F5
seg000:04E8                 add     byte_1FAB1, al
seg000:04EC                 cmp     byte_1FAB1, 3Bh ; ';'
seg000:04F1                 jbe     short loc_503
seg000:04F3                 sub     byte_1FAB1, 3Ch ; '<'
seg000:04F8                 cmp     byte_1FAB0, 0FFh
seg000:04FD                 jz      short loc_503
seg000:04FF                 inc     byte_1FAB0
seg000:0503
seg000:0503 loc_503:                                ; CODE XREF: sub_0+4F1␘j
seg000:0503                                         ; sub_0+4FD␘j
seg000:0503                 mov     al, byte_1FAB0
seg000:0506                 sub     ah, ah
seg000:0508                 mov     cl, byte_2A6F6
seg000:050C                 sub     ch, ch
seg000:050E                 add     ax, cx
seg000:0510                 cmp     ax, 100h
seg000:0513                 jnb     short loc_51E
seg000:0515                 mov     al, cl
seg000:0517                 add     byte_1FAB0, al
seg000:051B                 jmp     short loc_523
seg000:051B ; ---------------------------------------------------------------------------
seg000:051D                 align 2
seg000:051E
seg000:051E loc_51E:                                ; CODE XREF: sub_0+513␘j
seg000:051E                 mov     byte_1FAB0, 0FFh
seg000:0523
seg000:0523 loc_523:                                ; CODE XREF: sub_0+51B␘j
seg000:0523                 mov     al, byte_1FAAF
seg000:0526                 add     byte_1FAB9, al
seg000:052A                 cmp     byte_1FAB9, 3Bh ; ';'
seg000:052F                 jbe     short loc_53A
seg000:0531                 sub     byte_1FAB9, 3Ch ; '<'
seg000:0536                 inc     byte_1FAB8
seg000:053A
seg000:053A loc_53A:                                ; CODE XREF: sub_0+52F␘j
seg000:053A                 mov     al, byte_1FAAE
seg000:053D                 add     byte_1FAB8, al
seg000:0541                 mov     ax, 3Ch ; '<'
seg000:0544                 cwd
seg000:0545                 push    dx
seg000:0546                 push    ax
seg000:0547                 mov     al, byte_1FAB8
seg000:054A                 sub     ah, ah
seg000:054C                 sub     cx, cx
seg000:054E                 push    cx
seg000:054F                 push    ax
seg000:0550                 call    sub_1983C
seg000:0555                 mov     cl, byte_1FAB9
seg000:0559                 sub     ch, ch
seg000:055B                 add     ax, cx
seg000:055D                 adc     dx, 0
seg000:0560                 mov     [bp+var_6], ax
seg000:0563                 mov     [bp+var_4], dx
seg000:0566                 mov     ax, 1770h
seg000:0569                 cwd
seg000:056A                 push    dx
seg000:056B                 push    ax
seg000:056C                 mov     al, byte_1FAB0
seg000:056F                 sub     ah, ah
seg000:0571                 sub     cx, cx
seg000:0573                 push    cx
seg000:0574                 push    ax
seg000:0575                 call    sub_1983C
seg000:057A                 mov     cx, 64h ; 'd'
seg000:057D                 sub     bx, bx
seg000:057F                 push    bx
seg000:0580                 push    cx
seg000:0581                 mov     cl, byte_1FAB1
seg000:0585                 sub     ch, ch
seg000:0587                 push    bx
seg000:0588                 push    cx
seg000:0589                 mov     si, ax
seg000:058B                 mov     di, dx
seg000:058D                 call    sub_1983C
seg000:0592                 mov     cl, byte_1FAB2
seg000:0596                 sub     ch, ch
seg000:0598                 sub     bx, bx
seg000:059A                 mov     [bp+var_12], ax
seg000:059D                 mov     [bp+var_10], dx
seg000:05A0                 mov     ax, cx
seg000:05A2                 mov     dx, bx
seg000:05A4                 shl     cx, 1
seg000:05A6                 rcl     bx, 1
seg000:05A8                 shl     cx, 1
seg000:05AA                 rcl     bx, 1
seg000:05AC                 add     cx, ax
seg000:05AE                 adc     bx, dx
seg000:05B0                 shl     cx, 1
seg000:05B2                 rcl     bx, 1
seg000:05B4                 add     cx, [bp+var_12]
seg000:05B7                 adc     bx, [bp+var_10]
seg000:05BA                 add     cx, si
seg000:05BC                 adc     bx, di
seg000:05BE                 mov     [bp+var_A], cx
seg000:05C1                 mov     [bp+var_8], bx
seg000:05C4                 mov     ax, cx
seg000:05C6                 or      ax, bx
seg000:05C8                 jz      short loc_5EA
seg000:05CA                 push    bx
seg000:05CB                 push    cx
seg000:05CC                 mov     ax, 1770h
seg000:05CF                 cwd
seg000:05D0                 push    dx
seg000:05D1                 push    ax
seg000:05D2                 push    [bp+var_4]
seg000:05D5                 push    [bp+var_6]
seg000:05D8                 call    sub_1983C
seg000:05DD                 push    dx
seg000:05DE                 push    ax
seg000:05DF                 call    sub_197A0
seg000:05E4                 mov     byte_1FAB3, al
seg000:05E7                 jmp     short loc_5EF
seg000:05E7 ; ---------------------------------------------------------------------------
seg000:05E9                 align 2
seg000:05EA
seg000:05EA loc_5EA:                                ; CODE XREF: sub_0+5C8␘j
seg000:05EA                 mov     byte_1FAB3, 0
seg000:05EF
seg000:05EF loc_5EF:                                ; CODE XREF: sub_0+5E7␘j
seg000:05EF                 mov     al, byte ptr word_1FABA
seg000:05F2                 mov     byte_1FAB4, al
seg000:05F5                 mov     ax, word_1FABA
seg000:05F8                 mov     dx, word_1FABC
seg000:05FC                 mov     al, ah
seg000:05FE                 mov     ah, dl
seg000:0600                 mov     dl, dh
seg000:0602                 sub     dh, dh
seg000:0604                 mov     byte_1FAB5, al
seg000:0607                 mov     al, byte ptr word_1FABC
seg000:060A                 mov     byte_1FAB6, al
seg000:060D                 mov     ax, word_1FABA
seg000:0610                 mov     dx, word_1FABC
seg000:0614                 mov     cl, 18h
seg000:0616
seg000:0616 loc_616:                                ; CODE XREF: sub_0+61C␙j
seg000:0616                 shr     dx, 1
seg000:0618                 rcr     ax, 1
seg000:061A                 dec     cl
seg000:061C                 jnz     short loc_616
seg000:061E                 mov     byte_1FAB7, al
seg000:0621                 cmp     byte_1F168, 0
seg000:0626                 jz      short loc_63F
seg000:0628                 mov     al, byte_1FBEB
seg000:062B                 cmp     byte_1FBEA, al
seg000:062F                 jz      short loc_63F
seg000:0631                 mov     al, byte_2A6B6
seg000:0634                 sub     ah, ah
seg000:0636                 push    ax
seg000:0637                 call    sub_3A5C
seg000:063C                 add     sp, 2
seg000:063F
seg000:063F loc_63F:                                ; CODE XREF: sub_0+626␘j
seg000:063F                                         ; sub_0+62F␘j
seg000:063F                 sub     ax, ax
seg000:0641                 mov     word_1F17A, ax
seg000:0644                 push    ax
seg000:0645                 call    far ptr sub_16BB0
seg000:064A                 add     sp, 2
seg000:064D                 sub     ax, ax
seg000:064F                 push    ax
seg000:0650                 call    far ptr sub_16A93
seg000:0655                 add     sp, 2
seg000:0658                 mov     ax, 0C7h ; '¦'
seg000:065B                 push    ax
seg000:065C                 sub     ax, ax
seg000:065E                 push    ax
seg000:065F                 mov     ax, 13Fh
seg000:0662                 push    ax
seg000:0663                 sub     ax, ax
seg000:0665                 push    ax
seg000:0666                 call    far ptr sub_172BD
seg000:066B                 add     sp, 8
seg000:066E                 call    sub_3982
seg000:0673                 cmp     byte_1F168, 0
seg000:0678                 jz      short loc_683
seg000:067A                 mov     al, byte_1FBEB
seg000:067D                 cmp     byte_1FBEA, al
seg000:0681                 jnz     short loc_68E
seg000:0683
seg000:0683 loc_683:                                ; CODE XREF: sub_0+678␘j
seg000:0683                 sub     ax, ax
seg000:0685                 mov     word_1FABC, ax
seg000:0688                 mov     word_1FABA, ax
seg000:068B                 jmp     loc_799
seg000:068E ; ---------------------------------------------------------------------------
seg000:068E
seg000:068E loc_68E:                                ; CODE XREF: sub_0+681␘j
seg000:068E                 cmp     byte_1FABE, 0
seg000:0693                 jz      short loc_6A2
seg000:0695                 mov     al, byte_1FBEA
seg000:0698                 sub     ah, ah
seg000:069A                 mov     [bp+var_E], ax
seg000:069D                 add     byte_1FABE, 2
seg000:06A2
seg000:06A2 loc_6A2:                                ; CODE XREF: sub_0+693␘j
seg000:06A2                 call    sub_5C78
seg000:06A7                 call    sub_663E
seg000:06AC                 call    sub_1D78
seg000:06B1                 cmp     byte_1FBE8, 1
seg000:06B6                 jnz     short loc_6BF
seg000:06B8                 cmp     byte_1FBE9, 0
seg000:06BD                 jz      short loc_6C4
seg000:06BF
seg000:06BF loc_6BF:                                ; CODE XREF: sub_0+6B6␘j
seg000:06BF                 call    sub_5DB8
seg000:06C4
seg000:06C4 loc_6C4:                                ; CODE XREF: sub_0+6BD␘j
seg000:06C4                                         ; sub_0+6DB␙j
seg000:06C4                 inc     byte_1FAA4
seg000:06C8
seg000:06C8 loc_6C8:                                ; CODE XREF: sub_0+2CB␘j
seg000:06C8                 mov     al, byte_1FBE8
seg000:06CB                 cmp     byte_1FAA4, al
seg000:06CF                 ja      short loc_73A
seg000:06D1                 call    sub_1D48
seg000:06D6                 cmp     byte_1FABE, 0
seg000:06DB                 jz      short loc_6C4
seg000:06DD                 sub     ax, ax
seg000:06DF                 mov     word_1F162, ax
seg000:06E2                 mov     word_1F160, ax
seg000:06E5                 mov     [bp+var_C], ax
seg000:06E8
seg000:06E8 loc_6E8:                                ; CODE XREF: sub_0+6F7␙j
seg000:06E8                 mov     bx, [bp+var_C]
seg000:06EB                 mov     byte ptr [bx+9C6h], 0
seg000:06F0                 inc     [bp+var_C]
seg000:06F3                 cmp     [bp+var_C], 0Ah
seg000:06F7                 jl      short loc_6E8
seg000:06F9                 mov     word_1F166, 5
seg000:06FF                 sub     al, al
seg000:0701                 mov     byte_1FB55, al
seg000:0704                 mov     byte_1FB56, al
seg000:0707                 call    sub_76D6
seg000:070C                 call    sub_72DA
seg000:0711                 mov     al, byte_2A6F6
seg000:0714                 mov     byte_1FAA6, al
seg000:0717                 mov     al, byte_2A6F5
seg000:071A                 mov     byte_1FAA7, al
seg000:071D                 mov     al, byte_2A6F4
seg000:0720                 mov     byte_1FAA8, al
seg000:0723                 cmp     byte_284A4, 0
seg000:0728                 jnz     short loc_72D
seg000:072A                 jmp     loc_2CE
seg000:072D ; ---------------------------------------------------------------------------
seg000:072D
seg000:072D loc_72D:                                ; CODE XREF: sub_0+728␘j
seg000:072D                 mov     al, byte_2D84E
seg000:0730                 mov     byte_1FAAE, al
seg000:0733                 mov     al, byte_2C198
seg000:0736                 jmp     loc_335
seg000:0736 ; ---------------------------------------------------------------------------
seg000:0739                 align 2
seg000:073A
seg000:073A loc_73A:                                ; CODE XREF: sub_0+6CF␘j
seg000:073A                 inc     byte_1FBEA
seg000:073E
seg000:073E loc_73E:                                ; CODE XREF: sub_0+25A␘j
seg000:073E                 mov     al, byte_1FBEB
seg000:0741                 cmp     byte_1FBEA, al
seg000:0745                 jnb     short loc_74A
seg000:0747                 jmp     loc_292
seg000:074A ; ---------------------------------------------------------------------------
seg000:074A
seg000:074A loc_74A:                                ; CODE XREF: sub_0+745␘j
seg000:074A                 mov     word_1F166, 3
seg000:0750                 sub     ah, ah
seg000:0752                 dec     ax
seg000:0753                 cmp     [bp+var_E], ax
seg000:0756                 jnz     short loc_799
seg000:0758                 cmp     byte_1F168, 0
seg000:075D                 jz      short loc_799
seg000:075F                 mov     byte_1FAA4, 1
seg000:0764                 jmp     short loc_790
seg000:0766 ; ---------------------------------------------------------------------------
seg000:0766
seg000:0766 loc_766:                                ; CODE XREF: sub_0+797␙j
seg000:0766                 call    sub_1D48
seg000:076B                 cmp     byte_1FABE, 0
seg000:0770                 jz      short loc_78C
seg000:0772                 mov     ax, word_1FABA
seg000:0775                 mov     dx, word_1FABC
seg000:0779                 cmp     word_20FC9, dx
seg000:077D                 ja      short loc_78C
seg000:077F                 jb      short loc_787
seg000:0781                 cmp     word_20FC7, ax
seg000:0785                 ja      short loc_78C
seg000:0787
seg000:0787 loc_787:                                ; CODE XREF: sub_0+77F␘j
seg000:0787                 call    sub_27D0
seg000:078C
seg000:078C loc_78C:                                ; CODE XREF: sub_0+770␘j
seg000:078C                                         ; sub_0+77D␘j ...
seg000:078C                 inc     byte_1FAA4
seg000:0790
seg000:0790 loc_790:                                ; CODE XREF: sub_0+764␘j
seg000:0790                 mov     al, byte_1FBE8
seg000:0793                 cmp     byte_1FAA4, al
seg000:0797                 jbe     short loc_766
seg000:0799
seg000:0799 loc_799:                                ; CODE XREF: sub_0+68B␘j
seg000:0799                                         ; sub_0+756␘j ...
seg000:0799                 cmp     byte_1F168, 0
seg000:079E                 jz      short loc_7AA
seg000:07A0                 mov     word_2D89C, 0
seg000:07A6                 jmp     loc_150
seg000:07A6 ; ---------------------------------------------------------------------------
seg000:07A9                 align 2
seg000:07AA
seg000:07AA loc_7AA:                                ; CODE XREF: sub_0+79E␘j
seg000:07AA                 mov     word_1F166, 4
seg000:07B0                 sub     ax, ax
seg000:07B2                 mov     word_1FABC, ax
seg000:07B5                 mov     word_1FABA, ax
seg000:07B8                 jmp     loc_150
seg000:07B8 sub_0           endp
seg000:07B8
seg000:07B8 ; ---------------------------------------------------------------------------
seg000:07BB                 align 2
seg000:07BC
